dist: trusty
sudo: false

notifications:
  email: false

cache:
  yarn: true

env:
  global:
    - PATH=$HOME/.yarn/bin:$HOME/.local/bin:$PATH

language: node_js

node_js:
  - 7.4 # Sort with the version bundled in supported vscode.

before_install:
  # Use the latest yarnpkg because Travis' builtin yarn is not the latest.
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - which yarn # for debugging Travis
  - echo $PATH # for debugging Travis

script:
  - npm run compile